version: '3.8'

services:
  # Frontend service (Nginx to serve static files)
  frontend:
    image: nginx:alpine
    container_name: milesafe-frontend
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./:/usr/share/nginx/html
      - ./ssl:/etc/nginx/ssl
    depends_on:
      - backend
    restart: unless-stopped
    networks:
      - milesafe-network

  # Backend service
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: milesafe-backend
    ports:
      - "3000:3000"
      - "8080:3000"  # Map 8080 to 3000 for health checks
    environment:
      - NODE_ENV=production
      - PORT=3000
      - DB_HOST=${DB_HOST}
      - DB_USER=${DB_USER}
      - DB_PASS=${DB_PASS}
      - DB_NAME=${DB_NAME}
      - DB_PORT=${DB_PORT}
      - JWT_SECRET=${JWT_SECRET}
    depends_on:
      - database
    restart: unless-stopped
    networks:
      - milesafe-network
    volumes:
      - ./backend:/app
      - /app/node_modules

  # Database service
  database:
    image: mysql:8.0
    container_name: milesafe-database
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASS}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASS}
    volumes:
      - mysql_data:/var/lib/mysql
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "3306:3306"
    restart: unless-stopped
    networks:
      - milesafe-network

volumes:
  mysql_data:

networks:
  milesafe-network:
    driver: bridge
